[net]
git-fetch-with-cli = true

[build]
rustflags = ["-C", "target-feature=+crt-static"]

[target."x86_64-unknown-linux-musl"]
linker = "x86_64-linux-musl-g++"

[target."aarch64-unknown-linux-musl"]
linker = "aarch64-linux-musl-g++"